[package]
name = "rust-hash-playground"
version = "0.1.0"
edition = "2021"

[dependencies]
fxhash = "0.2.1"
hashbrown = "0.14.0"
rand = "0.8.5"
rustc-hash = "1.1.0"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "main"
harness = false
